<?
define('EMPTY_FUNCTION_ARG',10);

//Queue errors
define('EMPTY_QUEUE',99);
define('EMPTY_EVENT_TYPE',98);
define('EMPTY_PROJECT_ID',97);
define('EMPTY_WAREHOUSE_ID',96);
//define('EMPTY_EVENT_ID',95);
define('EMPTY_EVENT_DATA',94);
define('EVENT_NOT_PROCESSED',93);
define('EVENT_FACTORY_NOT_SET',92);
define('PUSH_EVENT_ERROR',91);
define('UNDEFINED_EVENT_TYPE',90);
define('WRONG_EVENT_ID',89);

//Core errors
define( 'EMPTY_PRODUCTS', 1000);
define( 'EMPTY_PRODUCT_AMOUNT', 1001);

define('ORDER_ID_NOT_NUMERIC',201);
define('PROJECT_ID_NOT_NUMERIC',202);
define('WAREHOUSE_ID_NOT_NUMERIC',203);
define('PRODUCT_ID_NOT_NUMERIC',204);
define('NO_PRODUCT_STATUS',205);

define('MYSQL_EMPTY_RESULT',301);
define('MYSQL_INSERT_ERROR',302);
define('MYSQL_ERROR',303);

define('NO_ENTITY_IN_STATUSES',401);
define('NO_TYPE_IN_STATUSES',402);
define('NO_STATUS_WITH_ID',403);

define('NO_ITEMS_ON_WAREHOUSE',501);

define('NOT_CANCELED_PRODUCTS_FOR_ORDER',601);
define('NO_PRODUCTS_FOR_ORDER',602);

define('CANT_CHECK_PRODUCTS_AVAILABILITY',3001);
define('NO_ORDER_ID',3002);

//Events errors
define('EVENT_DATA_NEW_ORDER_NO_PRODUCT',2001);
define('EVENT_DATA_NEW_ORDER_NO_ORDER_ID',2002);
define('EVENT_DATA_NEW_ORDER_NO_DEADLINE',2003);

define('EVENT_DATA_EDIT_ORDER_NO_ADD_NEW',2100);
define('EVENT_DATA_EDIT_ORDER_NO_CANCEL',2101);
define('EVENT_DATA_EDIT_ORDER_NO_CHANGE',2102);
define('EVENT_DATA_EDIT_ORDER_NO_PRODUCTS', 2103);
define('EVENT_DATA_EDIT_ORDER_NOT_UNIQUE_PRODUCTS', 2104);
define('EVENT_DATA_EDIT_ORDER_ORDER_NO_ORDER_ID',2105);

define('EVENT_DATA_CANCEL_ORDER_NO_ORDER_ID',2110);

define('EVENT_DATA_GET_PRODUCTS_BY_SKU_NO_SKU',2120);

define('EVENT_DATA_CREATE_NEW_ITEM_NO_TASK_ID',2130);
define('EVENT_DATA_CREATE_NEW_ITEM_NO_PRODUCT_ID',2131);
define('EVENT_DATA_CREATE_NEW_ITEM_NO_ADDRESS_ID',2132);

define('EVENT_DATA_COMPLETE_RECEIVE_TASK_NO_TASK_ID',2140);
define('EVENT_DATA_COMPLETE_RECEIVE_TASK_NO_AMOUNT',2141);
define('EVENT_DATA_COMPLETE_RECEIVE_TASK_NO_PRODUCTS',2142);
define( 'EVENT_DATA_COMPLETE_RECEIVE_TASK_NO_TN', 2143);
define('EVENT_DATA_COMPLETE_RECEIVE_TASK_NOT_UNIQUE_ITEMS',2144);
define('EVENT_DATA_COMPLETE_RECEIVE_TASK_NO_TN_NUMBER',2145);
define('EVENT_DATA_COMPLETE_RECEIVE_TASK_NO_INVOICE_NUMBER',2146);
define('EVENT_DATA_COMPLETE_RECEIVE_TASK_NO_TN_SUM', 2147);
define('EVENT_DATA_COMPLETE_RECEIVE_TASK_NO_TN_DATE', 2148);
define('EVENT_DATA_COMPLETE_RECEIVE_TASK_NO_SUPPLIER_ID', 2149);
define('EVENT_DATA_COMPLETE_RECEIVE_TASK_NO_KEY_IN_PRODUCT',2150);

define('EVENT_DATA_GET_ORDER_INFO_NO_ORDER_ID',2160);

define('EVENT_DATA_CREATE_ORDER_TASK_NO_USER_ID',2201);
define('EVENT_DATA_CANCEL_ORDER_TASK_NO_TASK_ID',2202);

define('PRINT_EVENT_DATA_PRINT_ITEM_BARCODE_NO_ITEM_ID',2301);



